# Time intervals
tint: ['2017-07-23T16:10:00.000000', '2017-07-23T18:10:00.000000']

tints: [['2017-07-23T16:54:14.000000', '2017-07-23T16:59:25.745247'],
        ['2017-07-23T17:17:11.000000', '2017-07-23T17:22:36.000000']]

data_path: "/Users/louisr/Documents/PhD/Y2/jet_fronts/data"

file_path: "./data/20170723_161000_20170723_181000_correlation_eis.nc"

# Flux Gate Magnetometer parameters
fgm:
  # Flux Gate Magnetometer data rate
  data_rate: "srvy"
  # Flux Gate Magnetometer data level
  level: "l2"

# Electric Double Probe (EDP) parameters
edp:
  # Electric Double Probe data rate
  data_rate: "fast"
  # Electric Double Probe data level
  level: "l2"

# Fast Plasma Investigation parameters
fpi:
  # Fast Plasma Investigation data rate
  data_rate: "fast"
  # Fast Plasma Investigation data level
  level: "l2"

# Hot Plasma Composition Analyser parameters
hpca:
  # Hot Plasma Composition Analyser data rate
  data_rate: "srvy"
  # Hot Plasma Composition Analyser data level
  level: "l2"

# Energetic Ion Spectrometer parameters
eis:
  # Energetic Ion Spectrometer data rate
  data_rate: "srvy"
  # Energetic Ion Spectrometer data level
  level: "l2"

# Fly Eye Energetic Particle Spectrometer parameters
feeps:
  # Fly Eye Energetic Particle Spectrometer data rate
  data_rate: "srvy"
  # Fly Eye Energetic Particle Spectrometer data level
  level: "l2"